### ISSUE TITLE
Installation Serveur 

### ISSUE THREAD

**Issue by Baldrani** [CatFishTeam/FacebookProject#22]
@guillaumepn  Il nous faut au moins les codes du VPS

**Comment by guillaumepn** [comment]
Accès VPS sur le channel discord #fb-project

**Comment by guillaumepn** [comment]
Accès Mysql sur le VPS aussi dans #fb-project

Le vps est configuré :  

* PHP 7 
* Mysql (Mariadb utilisé, mais c'est la même)
* Git
* Nginx
* Composer 
* Node (NPM)
